spring.datasource.url=jdbc:mysql://db:3306/wellie_database?serverTimezone=Asia/Seoul
spring.datasource.username=user
spring.datasource.password=${DB_PASSWORD}

# spring.datasource.policy.jdbc-url=jdbc:mysql://db2:3306/policy_database?serverTimezone=Asia/Seoul
# spring.datasource.policy.username=user
# spring.datasource.policy.password=${POLICY_USER_PASSWORD}
# spring.datasource.policy.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정 (데이터 보호를 위해 자동 수정 절대 금지.)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# 운영 환경 로그 레벨 (성능을 위해 경고 이상의 로그만 남김.)
logging.level.root=warn
